# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import game_routes_pb2 as game__routes__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game_routes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameRoutesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLobbies = channel.unary_unary(
                '/game_routes.GameRoutes/getLobbies',
                request_serializer=game__routes__pb2.Empty.SerializeToString,
                response_deserializer=game__routes__pb2.LobbyList.FromString,
                _registered_method=True)


class GameRoutesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getLobbies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameRoutesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLobbies': grpc.unary_unary_rpc_method_handler(
                    servicer.getLobbies,
                    request_deserializer=game__routes__pb2.Empty.FromString,
                    response_serializer=game__routes__pb2.LobbyList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game_routes.GameRoutes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('game_routes.GameRoutes', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameRoutes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getLobbies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_routes.GameRoutes/getLobbies',
            game__routes__pb2.Empty.SerializeToString,
            game__routes__pb2.LobbyList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
