# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game_routes.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'game_routes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11game_routes.proto\x12\x0bgame_routes\"\x07\n\x05\x45mpty\"\x1a\n\x07LobbyID\x12\x0f\n\x07lobbyID\x18\x01 \x01(\x05\"?\n\rLobbyMakeInfo\x12\x0e\n\x06userID\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08maxCount\x18\x03 \x01(\x05\"+\n\x08HybridID\x12\x0f\n\x07lobbyID\x18\x01 \x01(\x05\x12\x0e\n\x06userID\x18\x02 \x01(\x05\"f\n\x0cLobbyDetails\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x63urrMembers\x18\x03 \x01(\x05\x12\x12\n\nmaxMembers\x18\x04 \x01(\x05\x12\x0f\n\x07players\x18\x05 \x03(\x05\"B\n\tLobbyInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x63urrMembers\x18\x02 \x01(\x05\x12\x12\n\nmaxMembers\x18\x03 \x01(\x05\"D\n\tLobbyList\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\'\n\x07lobbies\x18\x02 \x03(\x0b\x32\x16.game_routes.LobbyInfo\"\x18\n\x06GameID\x12\x0e\n\x06gameID\x18\x01 \x01(\x05\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x05\"C\n\x07MapData\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12(\n\x07nations\x18\x02 \x03(\x0b\x32\x17.game_routes.PlayerData\"5\n\nPlayerData\x12\x12\n\npopulation\x18\x01 \x01(\x05\x12\x13\n\x0bprovinceIDs\x18\x02 \x03(\x05\x32\x9c\x04\n\nGameRoutes\x12\x38\n\ngetLobbies\x12\x12.game_routes.Empty\x1a\x16.game_routes.LobbyList\x12;\n\x08getLobby\x12\x14.game_routes.LobbyID\x1a\x19.game_routes.LobbyDetails\x12\x42\n\tmakeLobby\x12\x1a.game_routes.LobbyMakeInfo\x1a\x19.game_routes.LobbyDetails\x12=\n\tjoinLobby\x12\x15.game_routes.HybridID\x1a\x19.game_routes.LobbyDetails\x12\x38\n\nleaveLobby\x12\x15.game_routes.HybridID\x1a\x13.game_routes.Status\x12\x33\n\x07getGame\x12\x13.game_routes.GameID\x1a\x13.game_routes.Status\x12\x34\n\x07\x65ndGame\x12\x13.game_routes.GameID\x1a\x14.game_routes.MapData\x12\x38\n\x0c\x63ontinueGame\x12\x13.game_routes.GameID\x1a\x13.game_routes.Status\x12\x35\n\tcloseGame\x12\x13.game_routes.GameID\x1a\x13.game_routes.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_routes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_LOBBYID']._serialized_start=43
  _globals['_LOBBYID']._serialized_end=69
  _globals['_LOBBYMAKEINFO']._serialized_start=71
  _globals['_LOBBYMAKEINFO']._serialized_end=134
  _globals['_HYBRIDID']._serialized_start=136
  _globals['_HYBRIDID']._serialized_end=179
  _globals['_LOBBYDETAILS']._serialized_start=181
  _globals['_LOBBYDETAILS']._serialized_end=283
  _globals['_LOBBYINFO']._serialized_start=285
  _globals['_LOBBYINFO']._serialized_end=351
  _globals['_LOBBYLIST']._serialized_start=353
  _globals['_LOBBYLIST']._serialized_end=421
  _globals['_GAMEID']._serialized_start=423
  _globals['_GAMEID']._serialized_end=447
  _globals['_STATUS']._serialized_start=449
  _globals['_STATUS']._serialized_end=473
  _globals['_MAPDATA']._serialized_start=475
  _globals['_MAPDATA']._serialized_end=542
  _globals['_PLAYERDATA']._serialized_start=544
  _globals['_PLAYERDATA']._serialized_end=597
  _globals['_GAMEROUTES']._serialized_start=600
  _globals['_GAMEROUTES']._serialized_end=1140
# @@protoc_insertion_point(module_scope)
