services:
  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "6969:6969"

  user-service:
    build:
      context: ./User_Service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"