name: game_deployement

services:
  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    healthcheck:
      test: curl --fail http://localhost:6969/status || exit 1
      interval: 3s
      timeout: 5s
      retries: 5
  
  user-db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_data
      POSTGRES_USER: su_user
      POSTGRES_PASSWORD: secret_pass
    healthcheck:
      test: pg_isready -U su_user -d user_data
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./User_Service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgres://su_user:secret_pass@user-db:5432/user_data
      JWT_SECRET: user_token_secret
    healthcheck:
      test: grpc_health_probe -addr=:9000
      interval: 3s
      timeout: 5s
      retries: 5
    depends_on:
      user-db:
        condition: service_healthy

volumes:
  pg_data: