name: game_deployement

services:
  redis:
    image: redis:7
    command: redis-server
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5
  

  service-discovery:
    build:
      context: ./Service_Discovery
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    healthcheck:
      test: curl --fail http://localhost:4444/status
      interval: 3s
      timeout: 5s
      retries: 5
    stop_grace_period: 2s


  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    healthcheck:
      test: curl --fail http://localhost:6969/status
      interval: 3s
      timeout: 5s
      retries: 5
    environment:
      SERVICE_DISCOVERY_URL: http://service-discovery:4444
      JWT_SECRET: token_secret
    stop_grace_period: 2s
    depends_on:
      service-discovery:
        condition: service_healthy


  user-db:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user_data
      POSTGRES_USER: su_user
      POSTGRES_PASSWORD: secret_pass_user
    healthcheck:
      test: pg_isready -U su_user -d user_data
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - pg_user_data:/var/lib/postgresql/data


  game-db:
    image: postgres:17
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: game_data
      POSTGRES_USER: su_game
      POSTGRES_PASSWORD: secret_pass_game
    healthcheck:
      test: pg_isready -U su_game -d game_data
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - pg_game_data:/var/lib/postgresql/data


  user-service:
    build:
      context: ./User_Service
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "9000"
    environment:
      SERVICE_DISCOVERY_URL: http://service-discovery:4444
      DATABASE_URL: postgres://su_user:secret_pass_user@user-db:5432/user_data
      JWT_SECRET: token_secret
    healthcheck:
      test: grpc_health_probe -addr=:9000
      interval: 3s
      timeout: 5s
      retries: 5
    stop_grace_period: 2s
    depends_on:
      user-db:
        condition: service_healthy
      service-discovery:
        condition: service_healthy


  game-service:
    build:
      context: ./Game_Service
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "7000"
      - "7500"
    environment:
      SERVICE_DISCOVERY_URL: http://service-discovery:4444
      DATABASE_URL: postgres://su_game:secret_pass_game@game-db:5432/game_data
    healthcheck:
      test: grpc_health_probe -addr=:7000
      interval: 3s
      timeout: 5s
      retries: 5
    stop_grace_period: 2s
    depends_on:
      game-db:
        condition: service_healthy
      service-discovery:
        condition: service_healthy


volumes:
  pg_user_data:
  pg_game_data: