# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import user_routes_pb2 as user__routes__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in user_routes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserRoutesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.tryLogin = channel.unary_unary(
                '/user_routes.UserRoutes/tryLogin',
                request_serializer=user__routes__pb2.Credentials.SerializeToString,
                response_deserializer=user__routes__pb2.LoginConfirm.FromString,
                _registered_method=True)
        self.checkProfile = channel.unary_unary(
                '/user_routes.UserRoutes/checkProfile',
                request_serializer=user__routes__pb2.ProfileRequest.SerializeToString,
                response_deserializer=user__routes__pb2.UserInfo.FromString,
                _registered_method=True)
        self.sendFriendRequest = channel.unary_unary(
                '/user_routes.UserRoutes/sendFriendRequest',
                request_serializer=user__routes__pb2.RequestInfo.SerializeToString,
                response_deserializer=user__routes__pb2.Status.FromString,
                _registered_method=True)
        self.saveGameData = channel.unary_unary(
                '/user_routes.UserRoutes/saveGameData',
                request_serializer=user__routes__pb2.MapData.SerializeToString,
                response_deserializer=user__routes__pb2.Status.FromString,
                _registered_method=True)
        self.undoGameData = channel.unary_unary(
                '/user_routes.UserRoutes/undoGameData',
                request_serializer=user__routes__pb2.MapData.SerializeToString,
                response_deserializer=user__routes__pb2.Status.FromString,
                _registered_method=True)


class UserRoutesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def tryLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendFriendRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def saveGameData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def undoGameData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserRoutesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'tryLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.tryLogin,
                    request_deserializer=user__routes__pb2.Credentials.FromString,
                    response_serializer=user__routes__pb2.LoginConfirm.SerializeToString,
            ),
            'checkProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.checkProfile,
                    request_deserializer=user__routes__pb2.ProfileRequest.FromString,
                    response_serializer=user__routes__pb2.UserInfo.SerializeToString,
            ),
            'sendFriendRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.sendFriendRequest,
                    request_deserializer=user__routes__pb2.RequestInfo.FromString,
                    response_serializer=user__routes__pb2.Status.SerializeToString,
            ),
            'saveGameData': grpc.unary_unary_rpc_method_handler(
                    servicer.saveGameData,
                    request_deserializer=user__routes__pb2.MapData.FromString,
                    response_serializer=user__routes__pb2.Status.SerializeToString,
            ),
            'undoGameData': grpc.unary_unary_rpc_method_handler(
                    servicer.undoGameData,
                    request_deserializer=user__routes__pb2.MapData.FromString,
                    response_serializer=user__routes__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user_routes.UserRoutes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user_routes.UserRoutes', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserRoutes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def tryLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_routes.UserRoutes/tryLogin',
            user__routes__pb2.Credentials.SerializeToString,
            user__routes__pb2.LoginConfirm.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def checkProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_routes.UserRoutes/checkProfile',
            user__routes__pb2.ProfileRequest.SerializeToString,
            user__routes__pb2.UserInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sendFriendRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_routes.UserRoutes/sendFriendRequest',
            user__routes__pb2.RequestInfo.SerializeToString,
            user__routes__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def saveGameData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_routes.UserRoutes/saveGameData',
            user__routes__pb2.MapData.SerializeToString,
            user__routes__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def undoGameData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user_routes.UserRoutes/undoGameData',
            user__routes__pb2.MapData.SerializeToString,
            user__routes__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
